// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: merch/merch.proto

package merch

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_merch_merch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     *string                `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_merch_merch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_merch_merch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     *string                `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_merch_merch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_merch_merch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_merch_merch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type TokensPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokensPair) Reset() {
	*x = TokensPair{}
	mi := &file_merch_merch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensPair) ProtoMessage() {}

func (x *TokensPair) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensPair.ProtoReflect.Descriptor instead.
func (*TokensPair) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{6}
}

func (x *TokensPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokensPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_merch_merch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokensPair            `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_merch_merch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetTokens() *TokensPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokensPair            `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_merch_merch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshRequest) GetTokens() *TokensPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokensPair            `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_merch_merch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshResponse) GetTokens() *TokensPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_merch_merch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{11}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_merch_merch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	Price         *int32                 `protobuf:"varint,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	InStock       *int32                 `protobuf:"varint,6,opt,name=in_stock,json=inStock,proto3,oneof" json:"in_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_merch_merch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdateItemRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateItemRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateItemRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *UpdateItemRequest) GetPrice() int32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateItemRequest) GetInStock() int32 {
	if x != nil && x.InStock != nil {
		return *x.InStock
	}
	return 0
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	InStock       int32                  `protobuf:"varint,5,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_merch_merch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{14}
}

func (x *CreateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateItemRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateItemRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateItemRequest) GetInStock() int32 {
	if x != nil {
		return x.InStock
	}
	return 0
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_merch_merch_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{15}
}

func (x *GetItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogRequest) Reset() {
	*x = GetCatalogRequest{}
	mi := &file_merch_merch_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogRequest) ProtoMessage() {}

func (x *GetCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{16}
}

func (x *GetCatalogRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_merch_merch_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{17}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogResponse) Reset() {
	*x = GetCatalogResponse{}
	mi := &file_merch_merch_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogResponse) ProtoMessage() {}

func (x *GetCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogResponse) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{18}
}

func (x *GetCatalogResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	InStock       int32                  `protobuf:"varint,6,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_merch_merch_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{19}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Item) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetInStock() int32 {
	if x != nil {
		return x.InStock
	}
	return 0
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_merch_merch_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{20}
}

func (x *AddItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AddItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_merch_merch_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalQuantity int32                  `protobuf:"varint,2,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	TotalPrice    int32                  `protobuf:"varint,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_merch_merch_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{22}
}

func (x *GetCartResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCartResponse) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *GetCartResponse) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type GetCartTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalQuantity int32                  `protobuf:"varint,1,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	TotalPrice    int32                  `protobuf:"varint,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartTotalResponse) Reset() {
	*x = GetCartTotalResponse{}
	mi := &file_merch_merch_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartTotalResponse) ProtoMessage() {}

func (x *GetCartTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartTotalResponse.ProtoReflect.Descriptor instead.
func (*GetCartTotalResponse) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{23}
}

func (x *GetCartTotalResponse) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *GetCartTotalResponse) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_merch_merch_proto protoreflect.FileDescriptor

const file_merch_merch_proto_rawDesc = "" +
	"\n" +
	"\x11merch/merch.proto\x12\x15merch_store.api.merch\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xde\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc0\x01\n" +
	"\x11CreateUserRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02`\x01R\x05email\x12&\n" +
	"\bpassword\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\bR\bpassword\x12\"\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x04 \x01(\tH\x01R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\".\n" +
	"\x0eGetUserRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\"\x88\x01\n" +
	"\x11UpdateUserRequest\x12+\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\tfirstName\x88\x01\x01\x12)\n" +
	"\tlast_name\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x01R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\"1\n" +
	"\x11DeleteUserRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\"?\n" +
	"\fUserResponse\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.merch_store.api.merch.UserR\x04user\"^\n" +
	"\n" +
	"TokensPair\x12&\n" +
	"\faccess_token\x18\x01 \x01(\tB\x03\xe0A\x02R\vaccessToken\x12(\n" +
	"\rrefresh_token\x18\x02 \x01(\tB\x03\xe0A\x02R\frefreshToken\"Q\n" +
	"\fLoginRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02`\x01R\x05email\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tB\x03\xe0A\x02R\bpassword\"J\n" +
	"\rLoginResponse\x129\n" +
	"\x06tokens\x18\x01 \x01(\v2!.merch_store.api.merch.TokensPairR\x06tokens\"K\n" +
	"\x0eRefreshRequest\x129\n" +
	"\x06tokens\x18\x01 \x01(\v2!.merch_store.api.merch.TokensPairR\x06tokens\"L\n" +
	"\x0fRefreshResponse\x129\n" +
	"\x06tokens\x18\x01 \x01(\v2!.merch_store.api.merch.TokensPairR\x06tokens\"9\n" +
	"\rLogoutRequest\x12(\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\x03\xe0A\x02R\frefreshToken\"1\n" +
	"\x11DeleteItemRequest\x12\x1c\n" +
	"\aitem_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06itemId\"\x99\x02\n" +
	"\x11UpdateItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x04 \x01(\tH\x02R\bimageUrl\x88\x01\x01\x12\"\n" +
	"\x05price\x18\x05 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00H\x03R\x05price\x88\x01\x01\x12'\n" +
	"\bin_stock\x18\x06 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00H\x04R\ainStock\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_image_urlB\b\n" +
	"\x06_priceB\v\n" +
	"\t_in_stock\"\xc3\x01\n" +
	"\x11CreateItemRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x1d\n" +
	"\x05price\x18\x04 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x05price\x12\"\n" +
	"\bin_stock\x18\x05 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\ainStockB\x0e\n" +
	"\f_description\".\n" +
	"\x0eGetItemRequest\x12\x1c\n" +
	"\aitem_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06itemId\"V\n" +
	"\x11GetCatalogRequest\x12A\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2!.merch_store.api.merch.PaginationR\n" +
	"pagination\"4\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"G\n" +
	"\x12GetCatalogResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.merch_store.api.merch.ItemR\x05items\"\x90\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x19\n" +
	"\bin_stock\x18\x06 \x01(\x05R\ainStock\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"E\n" +
	"\x0eAddItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\",\n" +
	"\x11RemoveItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"\x8c\x01\n" +
	"\x0fGetCartResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.merch_store.api.merch.ItemR\x05items\x12%\n" +
	"\x0etotal_quantity\x18\x02 \x01(\x05R\rtotalQuantity\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x05R\n" +
	"totalPrice\"^\n" +
	"\x14GetCartTotalResponse\x12%\n" +
	"\x0etotal_quantity\x18\x01 \x01(\x05R\rtotalQuantity\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x05R\n" +
	"totalPrice2\xc3\x03\n" +
	"\vUserService\x12q\n" +
	"\n" +
	"CreateUser\x12(.merch_store.api.merch.CreateUserRequest\x1a#.merch_store.api.merch.UserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12r\n" +
	"\aGetUser\x12%.merch_store.api.merch.GetUserRequest\x1a#.merch_store.api.merch.UserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/{user_id}\x12Z\n" +
	"\x05GetMe\x12\x16.google.protobuf.Empty\x1a#.merch_store.api.merch.UserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/users/me\x12q\n" +
	"\n" +
	"UpdateUser\x12(.merch_store.api.merch.UpdateUserRequest\x1a#.merch_store.api.merch.UserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\t/v1/users2\xd7\x02\n" +
	"\vAuthService\x12m\n" +
	"\x05Login\x12#.merch_store.api.merch.LoginRequest\x1a$.merch_store.api.merch.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12u\n" +
	"\aRefresh\x12%.merch_store.api.merch.RefreshRequest\x1a&.merch_store.api.merch.RefreshResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/refresh\x12b\n" +
	"\x06Logout\x12$.merch_store.api.merch.LogoutRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout2\xbf\x04\n" +
	"\fMerchService\x12v\n" +
	"\n" +
	"GetCatalog\x12(.merch_store.api.merch.GetCatalogRequest\x1a).merch_store.api.merch.GetCatalogResponse\"\x13\x82\xd3\xe4\x93\x02\r\"\v/v1/catalog\x12j\n" +
	"\aGetItem\x12%.merch_store.api.merch.GetItemRequest\x1a\x1b.merch_store.api.merch.Item\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/items/{item_id}\x12i\n" +
	"\n" +
	"CreateItem\x12(.merch_store.api.merch.CreateItemRequest\x1a\x1b.merch_store.api.merch.Item\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/items\x12s\n" +
	"\n" +
	"UpdateItem\x12(.merch_store.api.merch.UpdateItemRequest\x1a\x1b.merch_store.api.merch.Item\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/items/{item_id}\x12k\n" +
	"\n" +
	"DeleteItem\x12(.merch_store.api.merch.DeleteItemRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/items/{item_id}2\xf1\x03\n" +
	"\vCartService\x12]\n" +
	"\aAddItem\x12%.merch_store.api.merch.AddItemRequest\x1a\x16.google.protobuf.Empty\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/cart\x12j\n" +
	"\n" +
	"RemoveItem\x12(.merch_store.api.merch.RemoveItemRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/cart/{item_id}\x12[\n" +
	"\aGetCart\x12\x16.google.protobuf.Empty\x1a&.merch_store.api.merch.GetCartResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/cart\x12M\n" +
	"\tClearCart\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x10\x82\xd3\xe4\x93\x02\n" +
	"*\b/v1/cart\x12k\n" +
	"\fGetCartTotal\x12\x16.google.protobuf.Empty\x1a+.merch_store.api.merch.GetCartTotalResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/cart/totalB\xd7\x01\x92A\xb6\x01\x125\n" +
	"\x0fMerch Store API\x12\x1bAPI for Merch Store service2\x051.0.0\"\x04/api*\x02\x01\x022\x10application/json:\x10application/jsonZA\n" +
	"?\n" +
	"\x06Bearer\x125\b\x02\x12\x1fBearer token for authentication\x1a\x0ex-access-token \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00Z\x1bmerch-store/pkg/merch;merchb\x06proto3"

var (
	file_merch_merch_proto_rawDescOnce sync.Once
	file_merch_merch_proto_rawDescData []byte
)

func file_merch_merch_proto_rawDescGZIP() []byte {
	file_merch_merch_proto_rawDescOnce.Do(func() {
		file_merch_merch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merch_merch_proto_rawDesc), len(file_merch_merch_proto_rawDesc)))
	})
	return file_merch_merch_proto_rawDescData
}

var file_merch_merch_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_merch_merch_proto_goTypes = []any{
	(*User)(nil),                  // 0: merch_store.api.merch.User
	(*CreateUserRequest)(nil),     // 1: merch_store.api.merch.CreateUserRequest
	(*GetUserRequest)(nil),        // 2: merch_store.api.merch.GetUserRequest
	(*UpdateUserRequest)(nil),     // 3: merch_store.api.merch.UpdateUserRequest
	(*DeleteUserRequest)(nil),     // 4: merch_store.api.merch.DeleteUserRequest
	(*UserResponse)(nil),          // 5: merch_store.api.merch.UserResponse
	(*TokensPair)(nil),            // 6: merch_store.api.merch.TokensPair
	(*LoginRequest)(nil),          // 7: merch_store.api.merch.LoginRequest
	(*LoginResponse)(nil),         // 8: merch_store.api.merch.LoginResponse
	(*RefreshRequest)(nil),        // 9: merch_store.api.merch.RefreshRequest
	(*RefreshResponse)(nil),       // 10: merch_store.api.merch.RefreshResponse
	(*LogoutRequest)(nil),         // 11: merch_store.api.merch.LogoutRequest
	(*DeleteItemRequest)(nil),     // 12: merch_store.api.merch.DeleteItemRequest
	(*UpdateItemRequest)(nil),     // 13: merch_store.api.merch.UpdateItemRequest
	(*CreateItemRequest)(nil),     // 14: merch_store.api.merch.CreateItemRequest
	(*GetItemRequest)(nil),        // 15: merch_store.api.merch.GetItemRequest
	(*GetCatalogRequest)(nil),     // 16: merch_store.api.merch.GetCatalogRequest
	(*Pagination)(nil),            // 17: merch_store.api.merch.Pagination
	(*GetCatalogResponse)(nil),    // 18: merch_store.api.merch.GetCatalogResponse
	(*Item)(nil),                  // 19: merch_store.api.merch.Item
	(*AddItemRequest)(nil),        // 20: merch_store.api.merch.AddItemRequest
	(*RemoveItemRequest)(nil),     // 21: merch_store.api.merch.RemoveItemRequest
	(*GetCartResponse)(nil),       // 22: merch_store.api.merch.GetCartResponse
	(*GetCartTotalResponse)(nil),  // 23: merch_store.api.merch.GetCartTotalResponse
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 25: google.protobuf.Empty
}
var file_merch_merch_proto_depIdxs = []int32{
	24, // 0: merch_store.api.merch.User.created_at:type_name -> google.protobuf.Timestamp
	24, // 1: merch_store.api.merch.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: merch_store.api.merch.UserResponse.user:type_name -> merch_store.api.merch.User
	6,  // 3: merch_store.api.merch.LoginResponse.tokens:type_name -> merch_store.api.merch.TokensPair
	6,  // 4: merch_store.api.merch.RefreshRequest.tokens:type_name -> merch_store.api.merch.TokensPair
	6,  // 5: merch_store.api.merch.RefreshResponse.tokens:type_name -> merch_store.api.merch.TokensPair
	17, // 6: merch_store.api.merch.GetCatalogRequest.pagination:type_name -> merch_store.api.merch.Pagination
	19, // 7: merch_store.api.merch.GetCatalogResponse.items:type_name -> merch_store.api.merch.Item
	24, // 8: merch_store.api.merch.Item.created_at:type_name -> google.protobuf.Timestamp
	24, // 9: merch_store.api.merch.Item.updated_at:type_name -> google.protobuf.Timestamp
	19, // 10: merch_store.api.merch.GetCartResponse.items:type_name -> merch_store.api.merch.Item
	1,  // 11: merch_store.api.merch.UserService.CreateUser:input_type -> merch_store.api.merch.CreateUserRequest
	2,  // 12: merch_store.api.merch.UserService.GetUser:input_type -> merch_store.api.merch.GetUserRequest
	25, // 13: merch_store.api.merch.UserService.GetMe:input_type -> google.protobuf.Empty
	3,  // 14: merch_store.api.merch.UserService.UpdateUser:input_type -> merch_store.api.merch.UpdateUserRequest
	7,  // 15: merch_store.api.merch.AuthService.Login:input_type -> merch_store.api.merch.LoginRequest
	9,  // 16: merch_store.api.merch.AuthService.Refresh:input_type -> merch_store.api.merch.RefreshRequest
	11, // 17: merch_store.api.merch.AuthService.Logout:input_type -> merch_store.api.merch.LogoutRequest
	16, // 18: merch_store.api.merch.MerchService.GetCatalog:input_type -> merch_store.api.merch.GetCatalogRequest
	15, // 19: merch_store.api.merch.MerchService.GetItem:input_type -> merch_store.api.merch.GetItemRequest
	14, // 20: merch_store.api.merch.MerchService.CreateItem:input_type -> merch_store.api.merch.CreateItemRequest
	13, // 21: merch_store.api.merch.MerchService.UpdateItem:input_type -> merch_store.api.merch.UpdateItemRequest
	12, // 22: merch_store.api.merch.MerchService.DeleteItem:input_type -> merch_store.api.merch.DeleteItemRequest
	20, // 23: merch_store.api.merch.CartService.AddItem:input_type -> merch_store.api.merch.AddItemRequest
	21, // 24: merch_store.api.merch.CartService.RemoveItem:input_type -> merch_store.api.merch.RemoveItemRequest
	25, // 25: merch_store.api.merch.CartService.GetCart:input_type -> google.protobuf.Empty
	25, // 26: merch_store.api.merch.CartService.ClearCart:input_type -> google.protobuf.Empty
	25, // 27: merch_store.api.merch.CartService.GetCartTotal:input_type -> google.protobuf.Empty
	5,  // 28: merch_store.api.merch.UserService.CreateUser:output_type -> merch_store.api.merch.UserResponse
	5,  // 29: merch_store.api.merch.UserService.GetUser:output_type -> merch_store.api.merch.UserResponse
	5,  // 30: merch_store.api.merch.UserService.GetMe:output_type -> merch_store.api.merch.UserResponse
	5,  // 31: merch_store.api.merch.UserService.UpdateUser:output_type -> merch_store.api.merch.UserResponse
	8,  // 32: merch_store.api.merch.AuthService.Login:output_type -> merch_store.api.merch.LoginResponse
	10, // 33: merch_store.api.merch.AuthService.Refresh:output_type -> merch_store.api.merch.RefreshResponse
	25, // 34: merch_store.api.merch.AuthService.Logout:output_type -> google.protobuf.Empty
	18, // 35: merch_store.api.merch.MerchService.GetCatalog:output_type -> merch_store.api.merch.GetCatalogResponse
	19, // 36: merch_store.api.merch.MerchService.GetItem:output_type -> merch_store.api.merch.Item
	19, // 37: merch_store.api.merch.MerchService.CreateItem:output_type -> merch_store.api.merch.Item
	19, // 38: merch_store.api.merch.MerchService.UpdateItem:output_type -> merch_store.api.merch.Item
	25, // 39: merch_store.api.merch.MerchService.DeleteItem:output_type -> google.protobuf.Empty
	25, // 40: merch_store.api.merch.CartService.AddItem:output_type -> google.protobuf.Empty
	25, // 41: merch_store.api.merch.CartService.RemoveItem:output_type -> google.protobuf.Empty
	22, // 42: merch_store.api.merch.CartService.GetCart:output_type -> merch_store.api.merch.GetCartResponse
	25, // 43: merch_store.api.merch.CartService.ClearCart:output_type -> google.protobuf.Empty
	23, // 44: merch_store.api.merch.CartService.GetCartTotal:output_type -> merch_store.api.merch.GetCartTotalResponse
	28, // [28:45] is the sub-list for method output_type
	11, // [11:28] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_merch_merch_proto_init() }
func file_merch_merch_proto_init() {
	if File_merch_merch_proto != nil {
		return
	}
	file_merch_merch_proto_msgTypes[1].OneofWrappers = []any{}
	file_merch_merch_proto_msgTypes[3].OneofWrappers = []any{}
	file_merch_merch_proto_msgTypes[13].OneofWrappers = []any{}
	file_merch_merch_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merch_merch_proto_rawDesc), len(file_merch_merch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_merch_merch_proto_goTypes,
		DependencyIndexes: file_merch_merch_proto_depIdxs,
		MessageInfos:      file_merch_merch_proto_msgTypes,
	}.Build()
	File_merch_merch_proto = out.File
	file_merch_merch_proto_goTypes = nil
	file_merch_merch_proto_depIdxs = nil
}
