// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: merch/merch.proto

package merch

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_merch_merch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     *string                `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_merch_merch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_merch_merch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     *string                `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_merch_merch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_merch_merch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_merch_merch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type TokensPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokensPair) Reset() {
	*x = TokensPair{}
	mi := &file_merch_merch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensPair) ProtoMessage() {}

func (x *TokensPair) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensPair.ProtoReflect.Descriptor instead.
func (*TokensPair) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{6}
}

func (x *TokensPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokensPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_merch_merch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokensPair            `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_merch_merch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetTokens() *TokensPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokensPair            `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_merch_merch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshRequest) GetTokens() *TokensPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokensPair            `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_merch_merch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshResponse) GetTokens() *TokensPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_merch_merch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{11}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Ответ с информацией о монетах, инвентаре и истории транзакций
type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coins         int32                  `protobuf:"varint,1,opt,name=coins,proto3" json:"coins,omitempty"`
	Inventory     []*InventoryItem       `protobuf:"bytes,2,rep,name=inventory,proto3" json:"inventory,omitempty"`
	CoinHistory   *CoinHistory           `protobuf:"bytes,3,opt,name=coin_history,json=coinHistory,proto3" json:"coin_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_merch_merch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{12}
}

func (x *InfoResponse) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *InfoResponse) GetInventory() []*InventoryItem {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *InfoResponse) GetCoinHistory() *CoinHistory {
	if x != nil {
		return x.CoinHistory
	}
	return nil
}

// Элемент инвентаря
type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_merch_merch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{13}
}

func (x *InventoryItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InventoryItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// История транзакций монет
type CoinHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      []*CoinRecord          `protobuf:"bytes,1,rep,name=received,proto3" json:"received,omitempty"`
	Sent          []*CoinRecord          `protobuf:"bytes,2,rep,name=sent,proto3" json:"sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinHistory) Reset() {
	*x = CoinHistory{}
	mi := &file_merch_merch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinHistory) ProtoMessage() {}

func (x *CoinHistory) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinHistory.ProtoReflect.Descriptor instead.
func (*CoinHistory) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{14}
}

func (x *CoinHistory) GetReceived() []*CoinRecord {
	if x != nil {
		return x.Received
	}
	return nil
}

func (x *CoinHistory) GetSent() []*CoinRecord {
	if x != nil {
		return x.Sent
	}
	return nil
}

// Запись о транзакции монет
type CoinRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinRecord) Reset() {
	*x = CoinRecord{}
	mi := &file_merch_merch_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinRecord) ProtoMessage() {}

func (x *CoinRecord) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinRecord.ProtoReflect.Descriptor instead.
func (*CoinRecord) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{15}
}

func (x *CoinRecord) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CoinRecord) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Запрос на отправку монет
type SendCoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUser        string                 `protobuf:"bytes,1,opt,name=to_user,json=toUser,proto3" json:"to_user,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCoinRequest) Reset() {
	*x = SendCoinRequest{}
	mi := &file_merch_merch_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCoinRequest) ProtoMessage() {}

func (x *SendCoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCoinRequest.ProtoReflect.Descriptor instead.
func (*SendCoinRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{16}
}

func (x *SendCoinRequest) GetToUser() string {
	if x != nil {
		return x.ToUser
	}
	return ""
}

func (x *SendCoinRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Запрос на покупку предмета
type BuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          string                 `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	mi := &file_merch_merch_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merch_merch_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_merch_merch_proto_rawDescGZIP(), []int{17}
}

func (x *BuyRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

var File_merch_merch_proto protoreflect.FileDescriptor

const file_merch_merch_proto_rawDesc = "" +
	"\n" +
	"\x11merch/merch.proto\x12\x15merch_store.api.merch\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xde\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc0\x01\n" +
	"\x11CreateUserRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02`\x01R\x05email\x12&\n" +
	"\bpassword\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\bR\bpassword\x12\"\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x04 \x01(\tH\x01R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\".\n" +
	"\x0eGetUserRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\"\x88\x01\n" +
	"\x11UpdateUserRequest\x12+\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\tfirstName\x88\x01\x01\x12)\n" +
	"\tlast_name\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x01R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\"1\n" +
	"\x11DeleteUserRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\"?\n" +
	"\fUserResponse\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.merch_store.api.merch.UserR\x04user\"^\n" +
	"\n" +
	"TokensPair\x12&\n" +
	"\faccess_token\x18\x01 \x01(\tB\x03\xe0A\x02R\vaccessToken\x12(\n" +
	"\rrefresh_token\x18\x02 \x01(\tB\x03\xe0A\x02R\frefreshToken\"Q\n" +
	"\fLoginRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02`\x01R\x05email\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tB\x03\xe0A\x02R\bpassword\"J\n" +
	"\rLoginResponse\x129\n" +
	"\x06tokens\x18\x01 \x01(\v2!.merch_store.api.merch.TokensPairR\x06tokens\"K\n" +
	"\x0eRefreshRequest\x129\n" +
	"\x06tokens\x18\x01 \x01(\v2!.merch_store.api.merch.TokensPairR\x06tokens\"L\n" +
	"\x0fRefreshResponse\x129\n" +
	"\x06tokens\x18\x01 \x01(\v2!.merch_store.api.merch.TokensPairR\x06tokens\"9\n" +
	"\rLogoutRequest\x12(\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\x03\xe0A\x02R\frefreshToken\"\xaf\x01\n" +
	"\fInfoResponse\x12\x14\n" +
	"\x05coins\x18\x01 \x01(\x05R\x05coins\x12B\n" +
	"\tinventory\x18\x02 \x03(\v2$.merch_store.api.merch.InventoryItemR\tinventory\x12E\n" +
	"\fcoin_history\x18\x03 \x01(\v2\".merch_store.api.merch.CoinHistoryR\vcoinHistory\"?\n" +
	"\rInventoryItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x83\x01\n" +
	"\vCoinHistory\x12=\n" +
	"\breceived\x18\x01 \x03(\v2!.merch_store.api.merch.CoinRecordR\breceived\x125\n" +
	"\x04sent\x18\x02 \x03(\v2!.merch_store.api.merch.CoinRecordR\x04sent\"8\n" +
	"\n" +
	"CoinRecord\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"L\n" +
	"\x0fSendCoinRequest\x12\x1c\n" +
	"\ato_user\x18\x01 \x01(\tB\x03\xe0A\x02R\x06toUser\x12\x1b\n" +
	"\x06amount\x18\x02 \x01(\x05B\x03\xe0A\x02R\x06amount\"%\n" +
	"\n" +
	"BuyRequest\x12\x17\n" +
	"\x04item\x18\x01 \x01(\tB\x03\xe0A\x02R\x04item2\xc3\x03\n" +
	"\vUserService\x12q\n" +
	"\n" +
	"CreateUser\x12(.merch_store.api.merch.CreateUserRequest\x1a#.merch_store.api.merch.UserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12r\n" +
	"\aGetUser\x12%.merch_store.api.merch.GetUserRequest\x1a#.merch_store.api.merch.UserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/{user_id}\x12Z\n" +
	"\x05GetMe\x12\x16.google.protobuf.Empty\x1a#.merch_store.api.merch.UserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/users/me\x12q\n" +
	"\n" +
	"UpdateUser\x12(.merch_store.api.merch.UpdateUserRequest\x1a#.merch_store.api.merch.UserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\t/v1/users2\xd7\x02\n" +
	"\vAuthService\x12m\n" +
	"\x05Login\x12#.merch_store.api.merch.LoginRequest\x1a$.merch_store.api.merch.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12u\n" +
	"\aRefresh\x12%.merch_store.api.merch.RefreshRequest\x1a&.merch_store.api.merch.RefreshResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/refresh\x12b\n" +
	"\x06Logout\x12$.merch_store.api.merch.LogoutRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout2\xa9\x02\n" +
	"\fMerchService\x12X\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a#.merch_store.api.merch.InfoResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/info\x12e\n" +
	"\bSendCoin\x12&.merch_store.api.merch.SendCoinRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/coins/send\x12X\n" +
	"\x03Buy\x12!.merch_store.api.merch.BuyRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/buy/{item}B\xd7\x01\x92A\xb6\x01\x125\n" +
	"\x0fMerch Store API\x12\x1bAPI for Merch Store service2\x051.0.0\"\x04/api*\x02\x01\x022\x10application/json:\x10application/jsonZA\n" +
	"?\n" +
	"\x06Bearer\x125\b\x02\x12\x1fBearer token for authentication\x1a\x0ex-access-token \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00Z\x1bmerch-store/pkg/merch;merchb\x06proto3"

var (
	file_merch_merch_proto_rawDescOnce sync.Once
	file_merch_merch_proto_rawDescData []byte
)

func file_merch_merch_proto_rawDescGZIP() []byte {
	file_merch_merch_proto_rawDescOnce.Do(func() {
		file_merch_merch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merch_merch_proto_rawDesc), len(file_merch_merch_proto_rawDesc)))
	})
	return file_merch_merch_proto_rawDescData
}

var file_merch_merch_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_merch_merch_proto_goTypes = []any{
	(*User)(nil),                  // 0: merch_store.api.merch.User
	(*CreateUserRequest)(nil),     // 1: merch_store.api.merch.CreateUserRequest
	(*GetUserRequest)(nil),        // 2: merch_store.api.merch.GetUserRequest
	(*UpdateUserRequest)(nil),     // 3: merch_store.api.merch.UpdateUserRequest
	(*DeleteUserRequest)(nil),     // 4: merch_store.api.merch.DeleteUserRequest
	(*UserResponse)(nil),          // 5: merch_store.api.merch.UserResponse
	(*TokensPair)(nil),            // 6: merch_store.api.merch.TokensPair
	(*LoginRequest)(nil),          // 7: merch_store.api.merch.LoginRequest
	(*LoginResponse)(nil),         // 8: merch_store.api.merch.LoginResponse
	(*RefreshRequest)(nil),        // 9: merch_store.api.merch.RefreshRequest
	(*RefreshResponse)(nil),       // 10: merch_store.api.merch.RefreshResponse
	(*LogoutRequest)(nil),         // 11: merch_store.api.merch.LogoutRequest
	(*InfoResponse)(nil),          // 12: merch_store.api.merch.InfoResponse
	(*InventoryItem)(nil),         // 13: merch_store.api.merch.InventoryItem
	(*CoinHistory)(nil),           // 14: merch_store.api.merch.CoinHistory
	(*CoinRecord)(nil),            // 15: merch_store.api.merch.CoinRecord
	(*SendCoinRequest)(nil),       // 16: merch_store.api.merch.SendCoinRequest
	(*BuyRequest)(nil),            // 17: merch_store.api.merch.BuyRequest
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 19: google.protobuf.Empty
}
var file_merch_merch_proto_depIdxs = []int32{
	18, // 0: merch_store.api.merch.User.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: merch_store.api.merch.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: merch_store.api.merch.UserResponse.user:type_name -> merch_store.api.merch.User
	6,  // 3: merch_store.api.merch.LoginResponse.tokens:type_name -> merch_store.api.merch.TokensPair
	6,  // 4: merch_store.api.merch.RefreshRequest.tokens:type_name -> merch_store.api.merch.TokensPair
	6,  // 5: merch_store.api.merch.RefreshResponse.tokens:type_name -> merch_store.api.merch.TokensPair
	13, // 6: merch_store.api.merch.InfoResponse.inventory:type_name -> merch_store.api.merch.InventoryItem
	14, // 7: merch_store.api.merch.InfoResponse.coin_history:type_name -> merch_store.api.merch.CoinHistory
	15, // 8: merch_store.api.merch.CoinHistory.received:type_name -> merch_store.api.merch.CoinRecord
	15, // 9: merch_store.api.merch.CoinHistory.sent:type_name -> merch_store.api.merch.CoinRecord
	1,  // 10: merch_store.api.merch.UserService.CreateUser:input_type -> merch_store.api.merch.CreateUserRequest
	2,  // 11: merch_store.api.merch.UserService.GetUser:input_type -> merch_store.api.merch.GetUserRequest
	19, // 12: merch_store.api.merch.UserService.GetMe:input_type -> google.protobuf.Empty
	3,  // 13: merch_store.api.merch.UserService.UpdateUser:input_type -> merch_store.api.merch.UpdateUserRequest
	7,  // 14: merch_store.api.merch.AuthService.Login:input_type -> merch_store.api.merch.LoginRequest
	9,  // 15: merch_store.api.merch.AuthService.Refresh:input_type -> merch_store.api.merch.RefreshRequest
	11, // 16: merch_store.api.merch.AuthService.Logout:input_type -> merch_store.api.merch.LogoutRequest
	19, // 17: merch_store.api.merch.MerchService.GetInfo:input_type -> google.protobuf.Empty
	16, // 18: merch_store.api.merch.MerchService.SendCoin:input_type -> merch_store.api.merch.SendCoinRequest
	17, // 19: merch_store.api.merch.MerchService.Buy:input_type -> merch_store.api.merch.BuyRequest
	5,  // 20: merch_store.api.merch.UserService.CreateUser:output_type -> merch_store.api.merch.UserResponse
	5,  // 21: merch_store.api.merch.UserService.GetUser:output_type -> merch_store.api.merch.UserResponse
	5,  // 22: merch_store.api.merch.UserService.GetMe:output_type -> merch_store.api.merch.UserResponse
	5,  // 23: merch_store.api.merch.UserService.UpdateUser:output_type -> merch_store.api.merch.UserResponse
	8,  // 24: merch_store.api.merch.AuthService.Login:output_type -> merch_store.api.merch.LoginResponse
	10, // 25: merch_store.api.merch.AuthService.Refresh:output_type -> merch_store.api.merch.RefreshResponse
	19, // 26: merch_store.api.merch.AuthService.Logout:output_type -> google.protobuf.Empty
	12, // 27: merch_store.api.merch.MerchService.GetInfo:output_type -> merch_store.api.merch.InfoResponse
	19, // 28: merch_store.api.merch.MerchService.SendCoin:output_type -> google.protobuf.Empty
	19, // 29: merch_store.api.merch.MerchService.Buy:output_type -> google.protobuf.Empty
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_merch_merch_proto_init() }
func file_merch_merch_proto_init() {
	if File_merch_merch_proto != nil {
		return
	}
	file_merch_merch_proto_msgTypes[1].OneofWrappers = []any{}
	file_merch_merch_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merch_merch_proto_rawDesc), len(file_merch_merch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_merch_merch_proto_goTypes,
		DependencyIndexes: file_merch_merch_proto_depIdxs,
		MessageInfos:      file_merch_merch_proto_msgTypes,
	}.Build()
	File_merch_merch_proto = out.File
	file_merch_merch_proto_goTypes = nil
	file_merch_merch_proto_depIdxs = nil
}
